export const JP_TYPES = [
  {
    id: 'normal',
    emoji: '👦',
    label: 'Normal JP',
    interest: 5,
    color: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    replies: [
      '👧 "Hmm... you\'re alright. I don\'t feel anything special. 😐"',
      '👧 "Oh it\'s just you... okay. 😑"',
      '👧 "I mean... you exist. That\'s something, right? 🤷‍♀️"',
      '👧 "Normal JP? More like \'nothing special\' JP. 😐"',
      '👧 "My heart rate didn\'t change. Not even a tiny bit. 📉"',
      '👧 "I\'ve seen more excitement from watching paint dry. 🎨💤"',
      '👧 "You\'re like plain rice... functional but boring. 🍚"',
      '👧 "My enthusiasm level: loading... loading... error 404. 🖥️"',
    ],
  },
  {
    id: 'smart',
    emoji: '😎',
    label: 'Smart & Lean JP',
    interest: 35,
    color: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    replies: [
      '👧 "Okay... now I\'m slightly impressed. 🤔✨"',
      '👧 "Brains AND looks? Hmm... continue. 😏"',
      '👧 "Smart JP has entered the chat. I\'m listening... 📚👀"',
      '👧 "You can solve equations? But can you solve my mood swings? 🤔😂"',
      '👧 "Okay Einstein, you have my attention for exactly 5 seconds. ⏱️"',
      '👧 "Smart is cute... but I need more data to confirm. 📊"',
      '👧 "My brain says interesting, my heart says \'need more info\'. 🧠❓"',
      '👧 "IQ points detected. Attraction level: slightly above zero. 📈"',
    ],
  },
  {
    id: 'fit',
    emoji: '💪',
    label: 'Fit JP',
    interest: 80,
    color: 'linear-gradient(135deg, #f5af19 0%, #f12711 100%)',
    replies: [
      '👧 "WAIT... who\'s this? 😳❤️"',
      '👧 "Those arms... I mean... what were we talking about? 💪🥵"',
      '👧 "Gym JP? More like MAKE-MY-HEART-RACE JP! 🏃‍♀️💓"',
      '👧 "I suddenly feel the need to go to the gym too... your gym specifically. 🏋️‍♂️😍"',
      '👧 "My knees are suddenly weak... is this a medical emergency or attraction? 🤒💕"',
      '👧 "6-pack JP just unlocked VIP access to my heart. 🎫❤️"',
      '👧 "Fit JP walked in and my standards walked out. 🚪😳"',
      '👧 "Someone call the fire department because FIT JP IS HERE! 🔥🚒"',
    ],
  },
  {
    id: 'dressed',
    emoji: '🤵',
    label: 'Well Dressed JP',
    interest: 50,
    color: 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)',
    replies: [
      '👧 "Looking classy today! 👀✨"',
      '👧 "Wait, is that a suit? On JP? I\'m confused AND impressed. 🤵😍"',
      '👧 "Formal JP just made my heart skip a dress code. 👗💓"',
      '👧 "Who styled you? I need to send them a thank you card. 💌"',
      '👧 "Well dressed JP could sell me anything at this point. 🛍️✨"',
      '👧 "You clean up nice! I mean... whatever... I\'m not looking! 👀😳"',
      '👧 "Dapper JP just crashed my \'I don\'t care\' firewall. 🧱💥"',
      '👧 "Is that cologne too? My defenses are weakening... 😤💕"',
    ],
  },
  {
    id: 'job',
    emoji: '💼',
    label: 'Job Holder JP',
    interest: 70,
    color: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    replies: [
      '👧 "Parents have suddenly become interested. 😂"',
      '👧 "Wait you have a JOB? *calls mom immediately* 📱😂"',
      '👧 "Employed JP? My mom just appeared out of nowhere with chai! 🍵👩"',
      '👧 "Stable income JP just became Shaadi.com worthy. 💍😂"',
      '👧 "Working JP? My parents\' rishta radar is BEEPING! 📡🚨"',
      '👧 "You get a salary?! My aunties are assembling. 🧕🧕🧕😂"',
      '👧 "Job holder JP? Suddenly my \'type\' has been updated. 📝✅"',
      '👧 "HR would like to offer you the position of \'potential boyfriend\'. 📋😏"',
    ],
  },
  {
    id: 'car',
    emoji: '🚗',
    label: 'Car Owner JP',
    interest: 60,
    color: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    replies: [
      '👧 "Free rides? That\'s tempting. 🚗🤣"',
      '👧 "Did someone say road trip? I\'m suddenly available 24/7! 🗺️😍"',
      '👧 "Car owner JP is literally driving into my heart. 🚗💨❤️"',
      '👧 "Wait... AC car? Sunroof? My standards just got picked up! 🚘✨"',
      '👧 "No more auto-rickshaw? You son of a JP, I\'m in! 🛺➡️🚗"',
      '👧 "Four wheels of attraction detected! Destination: my heart. 🧭💓"',
      '👧 "Late night drives with JP? I\'m not saying yes, but... where are we going? 🌃😏"',
      '👧 "Ola-Uber cancelled. JP Cab Service: always available. 🚕😂"',
    ],
  },
  {
    id: 'rich',
    emoji: '💰',
    label: 'Rich JP',
    interest: 90,
    color: 'linear-gradient(135deg, #f9d423 0%, #ff4e50 100%)',
    replies: [
      '👧 "My calculator is suddenly smiling. 💰😂"',
      '👧 "Rich JP? My shopping cart just got a HEARTBEAT! 🛒💓"',
      '👧 "Money can\'t buy love, but it can buy my ATTENTION. 🤑😂"',
      '👧 "💰 + JP = Nisha\'s sudden interest in economics. 📈"',
      '👧 "Rich JP walked in and my \'standards\' took a flight upgrade. ✈️😂"',
      '👧 "I\'m not materialistic... but Zara is calling. 🛍️🤭"',
      '👧 "Bank balance JP? I need to reconsider my life choices. 🏦💕"',
      '👧 "They say love is priceless, but a little price tag doesn\'t hurt! 🏷️😂"',
    ],
  },
  {
    id: 'cook',
    emoji: '🍳',
    label: 'JP Who Can Cook',
    interest: 85,
    color: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    replies: [
      '👧 "Marriage material unlocked! 🍳💍😂"',
      '👧 "You can cook BIRYANI?! Where\'s the mandap? Let\'s go! 🍛💒"',
      '👧 "Chef JP just unlocked the \'wifey material\' achievement... wait I mean... 👨‍🍳🏆"',
      '👧 "Roti, sabzi, AND dessert? I DO, I DO, I DO! 🍰💍😂"',
      '👧 "Cooking JP just bypassed all my relationship requirements. HIRED! 📋✅"',
      '👧 "My stomach just proposed on behalf of my heart. 🫄💕"',
      '👧 "A man who cooks? That\'s not a man, that\'s a LEGEND. 🦸‍♂️🍳"',
      '👧 "MasterChef JP? The recipe to my heart has been found! 📖❤️"',
    ],
  },
  {
    id: 'funny',
    emoji: '😂',
    label: 'Funny JP',
    interest: 75,
    color: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
    replies: [
      '👧 "Stop making me laugh! 😂❤️"',
      '👧 "My abs hurt from laughing. Is this a workout? 😂💪"',
      '👧 "Funny JP is dangerous. I can\'t even be mad at you! 😤😂"',
      '👧 "If humor was currency, JP would be a billionaire. 😂💰"',
      '👧 "STOP! My makeup is ruining from all this laughing! 😂💄"',
      '👧 "You\'re funny... annoyingly funny... attractively funny... wait what? 😂😳"',
      '👧 "My cheeks hurt but my heart is smiling. Is this legal? 😂❤️"',
      '👧 "Comedy JP just hacked into my feelings through humor. Firewall breached! 😂🔓"',
    ],
  },
  {
    id: 'caring',
    emoji: '❤️',
    label: 'Caring JP',
    interest: 88,
    color: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)',
    replies: [
      '👧 "Awww... that\'s actually sweet. 🥹💕"',
      '👧 "You remembered my favorite ice cream flavor? BRB, CRYING. 🍦😭💕"',
      '👧 "Caring JP? My cold heart just experienced global warming. 🌍❤️🔥"',
      '👧 "He asked if I ate? NOBODY ASKS IF I ATE! 😭🍽️💕"',
      '👧 "This JP puts the \'care\' in \'cardiac arrest\' because MY HEART! 💓🚑"',
      '👧 "Sweet JP just gave me emotional diabetes. Too sweet! 🍬😭"',
      '👧 "You checked up on me? Without me asking? WHO ARE YOU?! 👀💕"',
      '👧 "Caring JP bypassed the friendzone. Direct access to the heart zone. ❤️🗝️"',
    ],
  },
  {
    id: 'travel',
    emoji: '🌍',
    label: 'World Tour JP',
    interest: 82,
    color: 'linear-gradient(135deg, #89f7fe 0%, #66a6ff 100%)',
    replies: [
      '👧 "Packing my bags already! ✈️🤣"',
      '👧 "Paris? Bali? Maldives? Say less, I\'m IN! 🗺️😍"',
      '👧 "Travel JP just upgraded from \'maybe\' to \'PASSPORT READY\'! 🛂✈️"',
      '👧 "Wanderlust JP? My bags are packed, visa is ready, LET\'S GO! 🧳💨"',
      '👧 "You want to travel the world? With ME? *books tickets immediately* ✈️😍"',
      '👧 "Travel JP is my favorite JP. Where are we going first? 🗼🏖️"',
      '👧 "I don\'t need a man, I need a travel partner... oh wait, that\'s you! 🌏😏"',
      '👧 "Boarding pass to love: CONFIRMED. Seat next to JP: BOOKED. ✈️💺❤️"',
    ],
  },
  {
    id: 'perfect',
    emoji: '👑',
    label: 'Perfect JP',
    interest: 100,
    color: 'linear-gradient(135deg, #f7971e 0%, #ffd200 50%, #f7971e 100%)',
    replies: [
      '👧 "SYSTEM ERROR... TOO PERFECT! ❤️🤯💍"',
      '👧 "ERROR 404: REJECTION NOT FOUND. INITIATING LOVE PROTOCOL! 🤖❤️💍"',
      '👧 "PERFECT JP?! *Windows shutdown sound* My brain has crashed! 💻💥❤️"',
      '👧 "Is this real? Am I dreaming? SOMEONE PINCH ME! 😱💕👑"',
      '👧 "All systems override! Heart rate: MAXIMUM! Love level: INFINITE! 📊♾️❤️"',
      '👧 "Perfect JP doesn\'t exist, he can\'t hurt m— OH NO HE\'S HERE! 😍💍🚨"',
      '👧 "ALERT: Perfect specimen detected! Engaging ALL romantic protocols! 🚨❤️👑"',
      '👧 "Loading wedding plans... Loading honeymoon destinations... Loading baby names... 💒✈️👶😂"',
    ],
  },
];
